### ISSUE TITLE
The createdBy data model attribute should be in request header for API OAS

### ISSUE THREAD

**Issue by phriscage** [GoogleCloudPlatform/datashare-toolkit#143]
**Describe the bug**
The **createdBy** data model attribute should be in request header for API OAS. It is currently in the payload body. This will apply for all incoming resource requests payloads, but the data model response should still include the read-only attribute.

**Version**
[v0.3.0](https://github.com/GoogleCloudPlatform/datashare-toolkit/tree/v0.3.0)

**To Reproduce**
1. Go to 'v1alpha/docs'
2. Click on POST /policies and try to submit a new request
3. See error

**Expected behavior**
Add the **createdBy** attribute to the *x-gcp-account* header in the API OAS definitions

**Screenshots**
<img width="558" alt="Screen Shot 2020-05-31 at 10 40 54 AM" src="https://user-images.githubusercontent.com/1622265/83355202-e8a0e080-a32b-11ea-88e9-b296092c2292.png">

**Additional context**

**Comment by HeroicHitesh** [comment]
@phriscage From the code in v1alpha/src it seems this issue is fixed, if yes, it can be closed else, I would like to know where I can access v1alpha/docs to reproduce this issue

**Comment by mservidio** [comment]
Yes, looks to me like we updated to pass the createdBy in the x-gcp-account header already. The swagger documentation in the index.js files is missing it though.

**Comment by HeroicHitesh** [comment]
@mservidio Ok, I would like to work on this, is this how the createdBy should look like after this change
<img width="719" alt="Screenshot 2021-04-20 at 4 46 24 PM" src="https://user-images.githubusercontent.com/37622734/115387411-42d2ba80-a1f8-11eb-8b86-f448e4787d3e.png">

or is there any change in the description required?
cc @phriscage

**Comment by mservidio** [comment]
@HeroicHitesh, The 'x-gcp-account' header should in on the request header, not the response. There are a couple of endpoints for which documentation requires updating:

- /projects/:projectId/accounts
- /projects/:projectId/accounts/:accountId
- /projects/:projectId/datasets/:datasetId
- /projects/:projectId/datasets/:datasetId/views
- /projects/:projectId/datasets/:datasetId/views/:viewId'
- /projects/:projectId/products
- /projects/:projectId/policies
- /projects/:projectId/policies/:policyId

For the description, we could put something like 'GCP account name of the calling user'.
