### ISSUE TITLE
Add an initialization step for Datashare schema in setup documentation

### ISSUE THREAD

**Issue by phriscage** [GoogleCloudPlatform/datashare-toolkit#144]
**Describe the bug**
Add an initialization step for **Datashare** schema in setup documentation. This configuration setup step is currently missing in the README documentation.

**Version**
[v0.3.0](https://github.com/GoogleCloudPlatform/datashare-toolkit/tree/v0.3.0)

**Expected behavior**
Add an initialization step for **Datashare** schema in setup documentation. 

**Additional context**
Send a POST request to `/projects/{projectId}/admin:initSchema` after API is configured during setup.

**Comment by mservidio** [comment]
@phriscage - This is documented at https://github.com/GoogleCloudPlatform/datashare-toolkit/blob/master/frontend/README.md already. We could call it out more prominently, and in the future make the setup smoother with a wizard on initial launch?
