### ISSUE TITLE
Duplicate Search field placeholder text in multiple views 

### ISSUE THREAD

**Issue by phriscage** [GoogleCloudPlatform/datashare-toolkit#146]
**Describe the bug**
There is a duplicate Search field placeholder text in multiple views of the UI. This impacts the following views:
* datasets
* views
* accounts
* policies

**Version**
[v0.3.0](https://github.com/GoogleCloudPlatform/datashare-toolkit/tree/v0.3.0)

**To Reproduce**
1. Go to UI
2. Click on 'Accounts'
3. See error in Search Bar

**Expected behavior**
Only display one Search placeholder text

**Screenshots**
<img width="639" alt="Screen Shot 2020-05-31 at 3 12 58 PM" src="https://user-images.githubusercontent.com/1622265/83360723-878c0380-a351-11ea-8f95-776a3d035751.png">

**Desktop (please complete the following information):**
 - Browser - Chrome incognito

**Additional context**

**Comment by mservidio** [comment]
I'm guessing that the two 'search' texts that you're seeing are the one for when the text field is focused vs when it's not. Maybe it's a styling issue during some error condition. I'm unable to reproduce this one though, is it when you're not logged in?

**Comment by phriscage** [comment]
@mservidio Yes. These views are only accessible after user is logged in and authenticated. I have not tried with master yet, only v0.3.0 so it might be resolved already.

**Comment by mservidio** [comment]
From what I see so far, looks like this is an issue in the Cloud Run deployed version.
