### ISSUE TITLE
'Origin authentication failed' when posting to the accounts:register endpoint from Marketplace

### ISSUE THREAD

**Issue by mservidio** [GoogleCloudPlatform/datashare-toolkit#303]
**Describe the bug**
When attempting to register the account after a purchase, on the pop-up window navigating to: https://api.datashare-demo-2.fsi.joonix.net/v1alpha/projects/cds-demo-2/accounts:register receiving: 'Origin authentication failed.' error.

**Comment by phriscage** [comment]
This error is caused by a missmatch between the Marketplace SA JWT aud and the Istio AuthZ policy aud https://github.com/GoogleCloudPlatform/datashare-toolkit/blob/master/api/v1alpha/istio-manifests/1.4/authz/allow-marketplace-service-account-policy.tmpl.yaml#L17
