### ISSUE TITLE
Add Additional fields to Marketplace launch page

### ISSUE THREAD

**Issue by swilliams11** [GoogleCloudPlatform/datashare-toolkit#317]
The Datashare product has some new properties that should be included by the user.

The environment variables that must be set on the UI application when it is deployed to Cloud Run are shown below.  These should be set in the UI's Cloud Build function.  
```
{
  "VUE_APP_API_BASE_URL": "DOMAIN_NAME",
  "VUE_APP_PROJECT_ID": "PROJECT_ID",
  "VUE_APP_GOOGLE_APP_CLIENT_ID": "CLIENT_ID"
}
```

1. The domain name setup should be completed as part of the [prerequisites](https://github.com/GoogleCloudPlatform/datashare-toolkit/blob/master/marketplace/PREREQUISITES.md).  This can be a **required** field or **optional** field.  If it is optional, then the customer must complete this step after the deployment is completed.  
- Append  `/v1alpha` to the provided domain name

2. The project ID is already available in the Deployment Manager so we can auto-populate this environment variable.  

3. The client ID must be a new **required** field on the launch page.

**Comment by mservidio** [comment]
Also for the API, we need to set the env variable: UI_BASE_URL.

**Comment by mservidio** [comment]
We should also apply the ISTIO policies at this point, as we will have all of the necessary variables to do so.

**Comment by swilliams11** [comment]
Make sure to include the full name here for UI_BASE_URL
https://domainname.com

**Comment by swilliams11** [comment]
VUE_APP_API_BASE_URL=https://api.datashare-domain.com/v1alpha

**Comment by swilliams11** [comment]
When a user enters a UI domain name (domainname.com) then the following API is deployed with the following environment variable.
![image](https://user-images.githubusercontent.com/5075006/95922198-5c420800-0d78-11eb-8114-b06b5d8f3075.png)

When a user enters a UI domain name as https://datashare.com
![image](https://user-images.githubusercontent.com/5075006/95924648-995cc900-0d7d-11eb-97f8-d4047de29ea9.png)


When a user enters a UI domain name as http://datashare.com
![image](https://user-images.githubusercontent.com/5075006/95924005-5a7a4380-0d7c-11eb-8060-c3ed436a6e31.png)


If the UI domain name is not included by the user, then the environment variable will not be included on the API. 
![image](https://user-images.githubusercontent.com/5075006/95916043-affb2400-0d6d-11eb-93a3-ae67b6be000e.png)

**Comment by swilliams11** [comment]
# API domain name
When a user enters http://api.datashare.com, then the deployment fails immediately.
![image](https://user-images.githubusercontent.com/5075006/95927943-c7460b80-0d85-11eb-969f-6189e51766fd.png)

When user enters https://api.domain.com, then
![image](https://user-images.githubusercontent.com/5075006/95989853-6a336f80-0df0-11eb-8970-40773ab58e9f.png)
![image](https://user-images.githubusercontent.com/5075006/95989835-63a4f800-0df0-11eb-88b2-874d6355a042.png)


When user enters api.domain.com, then
![image](https://user-images.githubusercontent.com/5075006/95928998-72f05b00-0d88-11eb-9085-d518f1f1d302.png)
