### ISSUE TITLE
Update 'Role launch stage' for datashare mgr role to GA

### ISSUE THREAD

**Issue by mservidio** [GoogleCloudPlatform/datashare-toolkit#450]
Update 'Role launch stage' for datashare mgr role to GA

**Comment by mservidio** [comment]
@phriscage Do you know is there any reason we couldn't make this change?
https://github.com/GoogleCloudPlatform/datashare-toolkit/blob/master/api/config/ds-api-mgr-role-definition.yaml

**Comment by phriscage** [comment]
Hi @mservidio,

No, I do not foresee any issues switching the custom IAM role launch stage to *GA*. I believe the initial thought process was to follow the launch cycle guidelines for custom IAM roles [here](https://cloud.google.com/iam/docs/understanding-custom-roles#testing_and_deploying) while the role was in a testing phase.

Thanks,
Chris
