### ISSUE TITLE
GKE Support for 1.16

### ISSUE THREAD

**Issue by cejj** [GoogleCloudPlatform/datashare-toolkit#506]
When I use the Marketplace VM solution I am getting the below error

`{"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"No valid versions with the prefix \"1.16\" found.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1/projects/jayadeep-etl-platform/zones/us-central1-a/clusters","httpMethod":"POST"}}`

Looks like GKE version needs to be updated in `cluster.py` script from 1.16 to 1.18 as per the release notes present here - https://cloud.google.com/kubernetes-engine/docs/release-notes

**Comment by swilliams11** [comment]
Thanks @cejj . I'll review this.

**Comment by swilliams11** [comment]
I reviewed our [documentation](https://cloud.google.com/service-mesh/docs/supported-features#supported_versions) for support Anthos Service Mesh (ASM) and release version 1.4 is no longer support.   We currently install 1.4.10 during the VM startup script, which is the same version used by Cloud Run for Anthos (we enable this to deploy the UI).  

I updated `cluster.py` to install the latest release of GKE 1.18, and tested that the installation of Istio 1.4.10 was successful.  However, given that this version is not supported and there is a new release of 1.9 (released in March of 2021), then we should install the latest version of Istio ASM.

## New GKE Cluster
I decided to test what installation of Istio is installed on on a GKE cluster (1.19) when I manually create the cluster with Cloud Run for Anthos installed on it.  I enabled the beta release of Istio manually, by clicking on the cluster and clicking the edit button next to Istio beta.  

When I execute the following command:
```
kubectl -n gke-system get deployments istio-pilot                         -o jsonpath="{.spec.template.spec.containers[0].image}"
```

I get the following result. It looks like the same 1.4.10 Istio version is installed with Cloud Run. But I think this is the Istio version installed as part of Cloud Run. 
```
gke.gcr.io/asm/pilot:1.4.10-asm.18
```

If you click on Object browser you will get a different Istio release version. I'm trying to determine if this is the release version that is automatically installed when I enabled Istio on the GKE cluster. 
![image](https://user-images.githubusercontent.com/5075006/120855335-f3481400-c543-11eb-8da6-2103833ad318.png)


**I'm also trying to determine if Istio 1.4.10 will run on GKE 1.18.** 
https://cloud.google.com/istio/docs/istio-on-gke/versions

**Comment by swilliams11** [comment]
It looks like 1.4.10-gke.8 can run on GKE 1.18.15-gke.3+
