### ISSUE TITLE
Deployment fails when regions without service availability is chosen

### ISSUE THREAD

**Issue by n0531m** [GoogleCloudPlatform/datashare-toolkit#513]
**Describe the bug**

DataShare is depending on services such as Cloud Functions and thus fails to be deployment when Google Cloud regions without these services (eg. Singapore (asia-southeast1) ) is chosen. 

It would be helpful to have a region config for Functions separately. (in the case above, Jakarta (asia-southeast2) can be the closest alternative) 
Otherwise, regions that DataShare cannot be deployed should be excluded from options.

**Comment by swilliams11** [comment]
Thanks for the request @n0531m.  I'll take a look at now.

**Comment by swilliams11** [comment]
I added this functionality to the 0.7.1 release.  However, the Marketplace team does not release solutions in a queued manner, so the 0.7.1 release would replace the 0.7.0 release and the changes included in 0.7.0 will be included in 0.7.1 Marketplace release.  This means that the next release will be 0.7.1.
