### ISSUE TITLE
Update sample domain in docs

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/datashare-toolkit#621]
The joonix.net domain isn't meant to be used in public documentation. Please replace it with a different domain that follows Google's guidelines, such as `example.com`: https://developers.google.com/style/examples#example-domain-names

This change also requires updates to screenshots, such as the ones in https://github.com/GoogleCloudPlatform/datashare-toolkit/blob/master/DOMAIN_SETUP.md.

**Comment by mservidio** [comment]
Thanks @hegemonic. We're currently working on updating all of the documentation for a separate effort. We'll rename the domains per the guideline.
